clear;close all;clc;
load('dataset_pd.mat');
load('dataset_upd.mat');
% dataset_pd.pitch=dataset_pd.pitch-mean(dataset_pd.pitch);
% dataset_pd.roll=dataset_pd.roll-mean(dataset_pd.roll);
% dataset_pd.yaw=dataset_pd.yaw-mean(dataset_pd.yaw);
figure;subplot(221);
plot(dataset_pd.time', [dataset_pd.pitch';dataset_pd.roll';dataset_pd.yaw']);
xlabel("time");
ylabel("attitude");
title('时域姿态图\_模拟帕金森');
legend('pitch', 'roll', 'yaw');
dataset_pitch_f = fft(dataset_pd{:, "pitch"});
pitch_fft_shift = fftshift(dataset_pitch_f);
dataset_roll_f = fft(dataset_pd{:, "roll"});
roll_fft_shift = fftshift(dataset_roll_f);
dataset_yaw_f = fft(dataset_pd{:, "yaw"});
yaw_fft_shift = fftshift(dataset_yaw_f);
Fs = 1 / 0.03;
f = Fs * (- length(dataset_pd{:, "pitch"}) / 2 : length(dataset_pd{:, "pitch"}) / 2 - 1) / length(dataset_pd{:, "pitch"});
subplot(222);
plot(f, abs(pitch_fft_shift), f, abs(roll_fft_shift), f, abs(yaw_fft_shift));
xlabel("Fz");ylabel("Magnitude");title('频域姿态图\_模拟帕金森');legend('pitch', 'roll', 'yaw');
subplot(223);
plot(dataset_upd{:, "time"}, dataset_upd{:, "pitch"}, dataset_upd{:, "time"}, dataset_upd{:, "roll"}, dataset_upd{:, "time"}, dataset_upd{:, "yaw"});
xlabel("time");ylabel("attitude");title('时域姿态图\_正常');legend('pitch', 'roll', 'yaw');
datasetu_pitch_f = fft(dataset_upd{:, "pitch"});
pitch_fft_shift_u = fftshift(datasetu_pitch_f);
datasetu_roll_f = fft(dataset_upd{:, "roll"});
roll_fft_shift_u = fftshift(datasetu_roll_f);
datasetu_yaw_f = fft(dataset_upd{:, "yaw"});
yaw_fft_shift_u = fftshift(datasetu_yaw_f);
f2 = Fs * (- length(dataset_upd{:, "pitch"}) / 2 : length(dataset_upd{:, "pitch"}) / 2 - 1) / length(dataset_upd{:, "pitch"});
subplot(224);
plot(f2, abs(pitch_fft_shift_u), f2, abs(roll_fft_shift_u), f2, abs(yaw_fft_shift_u));
xlabel("Fz");ylabel("Magnitude");title('频域姿态图\_正常');legend('pitch', 'roll', 'yaw');
